### PR TITLE
Gitlab Connector

### LINKED ISSUE #367: feat: Add Gitlab integration to ticketing vertical
feat: Add Gitlab integration to ticketing vertical

Expected objets are: 

- [x] Collections
- [x] Comments
- [ ] Tags
  - It is not compatible with Panora's Unified Model. The tag should be associated with the ticket (issue). However, for GitLab, tags are associated with individual projects, which makes it incompatible with Panora's Unified Model.
- [x] Tickets
- [x] Users

Please find details about how to build integrations [here](https://docs.panora.dev/open-source/contributors) . Our [discord](https://discord.gg/feRW57Ym3D)  community is also a great place to get support!

### PR DESCRIPTION
**Pull request by mit-27**
- Closes #367  
- **Objects**
   - [x] Collections
   - [x] Comments
   - [ ] Tags 
       - It is not compatible with Panora's Unified Model. The tag should be associated with the ticket (issue). However, for GitLab, tags are associated with individual projects, which makes it incompatible with Panora's Unified Model.
   - [x] Tickets
   - [x] Users

### CODE REVIEW

**Comment by Rutik7066** [comment]
Hi @mit-27  may pick this code to solve #367

**Comment by mit-27** [comment]
Sorry @Rutik7066, I already on it.Could you please pick any other issue if possible?

**Comment by rajeshj11** [comment]
@mit-27 I think you have missed the below issues. 
1. For every request, the response we will get is paginated data. (which is limited to 20 only).
2. When using pagination we need to call the API multiple times. sometimes we are getting server 500 internal error which needs a re-try mechanism that is not handled.
I have worked on the pagination and re-try mechanism as part of contributing to this feature. If you agree I can take your branch and cherry-pick my pagination changes into your branch(if not needed refer to this  link. https://docs.gitlab.com/ee/api/rest/index.html#keyset-based-pagination)

**Comment by mit-27** [comment]
Hi @rajeshj11,thank you for addressing the issues. However, we will handle pagination later, and we have also created an issue for it. If you would like to work on it, feel free to pick it up once it is merged.

**Pull request merged**
