### PR TITLE
Add Attio CRM integration

### LINKED ISSUE #316: feat: Add Attio to CRM Unified API
More details about building integrations available [here](https://docs.panora.dev/open-source/contributors)

### PR DESCRIPTION
**Pull request by mit-27**
- Closes #316 

**Pending Tasks**

- [x] Add image for Attio CRM
- [ ] Add Company object to CRM
- [ ] Check Mapping of attributes to unified Data and vice versa
- [x] Test Connection Creation 
- [x] Test Sync Contacts
- [ ] Test Add Contact
- [ ] Discover a method to substitute the client_id value within the providersConfig constant located in packages/shared/src/utils.ts file. (Failure to provide a valid client_id will result in improper functioning of the connection flow.)

## Summary by CodeRabbit

- **New Features**
	- Added support for Attio CRM, including OAuth authentication, contact synchronization, and configuration settings.
- **Enhancements**
	- Improved logging for better debugging and monitoring.
- **Refactor**
	- Updated environment configurations and internal service registration for enhanced modularity and maintainability.
- **Documentation**
	- Expanded the enum and type definitions to include Attio-specific configurations and data structures.

### CODE REVIEW

**Comment by mit-27** [comment]
Hello @rflihxyz, This pull request exclusively contains contacts from Attio CRM. Would you like me to also implement it for the Company object?

**Comment by naelob** [comment]
> Hello @rflihxyz, This pull request exclusively contains contacts from Attio CRM. Would you like me to also implement it for the Company object?

Im checking the validity of the code on my side, i'll let you know within 1 hour !

**Comment by naelob** [comment]
@mit-27 Could you in the meantime, spot all missing things you had to check by yourself when building this integration ? 

Thanky ou very much !

**Comment by mit-27** [comment]
> > Hello @rflihxyz, This pull request exclusively contains contacts from Attio CRM. Would you like me to also implement it for the Company object?
> 
> Im checking the validity of the code on my side, i'll let you know within 1 hour !
I think there are issues with addContact method.  Could you also double check the dataModel which I mentioned in types.ts file. I am not sure whether it works for both AttioContactInput and AttioContactOutput. Thanks :)

**Comment by mit-27** [comment]
> @mit-27 Could you in the meantime, spot all missing things you had to check by yourself when building this integration ?
> 
> Thanky ou very much !

Sure ;)

**Comment by naelob** [comment]
> > @mit-27 Could you in the meantime, spot all missing things you had to check by yourself when building this integration ?
> > Thanky ou very much !
> 
> Sure ;)

btw could you share with me the .env vars for ATTIO ? You can send that over slack in private (send me your address mail so i can invite you on slack)

**Comment by mit-27** [comment]
> > > @mit-27 Could you in the meantime, spot all missing things you had to check by yourself when building this integration ?
> > > Thanky ou very much !
> > 
> > 
> > Sure ;)
> 
> btw could you share with me the .env vars for ATTIO ? You can send that over slack in private (send me your address mail so i can invite you on slack)

It is meetsuthar64@gmail.com

**Pull request merged**
