### PR TITLE
:art: Externalise index.ts logic under ticketing/**/services

### PR DESCRIPTION
**Pull request by Gift-Stack**
Commences solution to fix issue: #222 

## Summary by CodeRabbit

- **New Features**
  - Enhanced ticket and user synchronization across various services with streamlined processes.
  - Improved error handling and response mapping for ticket and user services.

- **Refactor**
  - Simplified constructors for `FrontService`, `GithubService`, `HubspotService`, and `ZendeskService` classes.
  - Removed redundant `syncTickets` and `syncUsers` methods, replaced with more efficient implementations.

- **Bug Fixes**
  - Fixed issues with ticket and user data syncing to ensure up-to-date information is displayed.

### CODE REVIEW

**Comment by naelob** [comment]
@Gift-Stack 
Ok i reviewed what you've done ! Its pretty impressive ! Thank you very much. 
Im just fixing other bugs in the code and I'll merge this work !

**Comment by Gift-Stack** [comment]
> @Gift-Stack Ok i reviewed what you've done ! Its pretty impressive ! Thank you very much. Im just fixing other bugs in the code and I'll merge this work ! I'll use this across the entire codebase, even for POST requests. If you are excited to work on it let me know ;)

Hi! Sure, I’ll love to take it up! I initially just wanted to confirm if that was the solution you were looking for. 

Also, since this PR isn’t merged, should I create smaller PRs to this one and then we can merge the entire thing to main when we’ve completed all the files in the `ticketing/**/services` folder

**Comment by naelob** [comment]
@Gift-Stack Hey ! before merging could you add commits to all services not only the ones in ticketing so it stays consistent across the codebase ? 

thanks again !

**Comment by Gift-Stack** [comment]
> @Gift-Stack Hey ! before merging could you add commits to all services not only the ones in ticketing so it stays consistent across the codebase ?
> 
> thanks again !

Sure : ) Would update them this weekend.

**Pull request closed without merging**
