### PR TITLE
Add auth credentials feature

### LINKED ISSUE #333: Add integration's setup Credentials Page
**Problem**
- If the end user wants to use the 3rd Party integration then he has to edit `.env` file and `utils.ts` file from shared packages to configure the 3rd Party's credentials (ClientID, secret, etc).

**Solution**
- Provide the page where users can set their 3rd Party's credentials.
- **Storing and accessing the credentials from Database** - Link the user_id of the logged-in user with the credentials of each third-party service.

### PR DESCRIPTION
**Pull request by mit-27**
- Closes #333 

## Summary by CodeRabbit

- **New Features**
  - Enhanced OAuth2 authentication handling to improve security and logging.
  - Added consolidation functionality for provider arrays to streamline data management.
  - Introduced new methods for managing connection strategies in the API.

- **Enhancements**
  - Updated authentication strategy definitions and utility functions for better clarity and functionality.
  - Improved layout handling in the client application to enhance user session management.

- **Bug Fixes**
  - Fixed issues with environment variable formatting in Docker configurations.

- **Refactor**
  - Code refactoring to improve readability and maintainability across multiple modules.

- **Style**
  - Minor formatting adjustments in various configuration files and codebases to enhance code consistency.

### CODE REVIEW

**Comment by rflihxyz** [comment]
Hey, can you guys make sure the project builds when running:

``
BUILDKIT_PROGRESS=plain docker compose -f docker-compose.source.yml up
`` 

On my end it seems there is an issue with the Magic Link project?

**Comment by mit-27** [comment]
Yes sure. Now on, I will make sure that it builds successfully. I am going to fix it. Thank you

**Comment by rflihxyz** [comment]
> I have locally tested it, and the build was successful. Could you please double-check it again, @rflihxyz ?

I tried it using a github codespace, following the normal self-hosting procedure (cp .env.example .env && BUILDKIT_PROGRESS=plain docker compose -f docker-compose.source.yml up)

Did you have success running the project that way?

**Comment by mit-27** [comment]
> > I have locally tested it, and the build was successful. Could you please double-check it again, @rflihxyz ?
> 
> I tried it using a github codespace, following the normal self-hosting procedure (cp .env.example .env && BUILDKIT_PROGRESS=plain docker compose -f docker-compose.source.yml up)
> 
> Did you have success running the project that way?

Yes, I tested and it is running.

**Pull request closed without merging**
